// Code generated by protoc-gen-go. DO NOT EDIT.
// source: salute/salute.proto

/*
Package salute is a generated protocol buffer package.

Define that the generated files will have the package salute

It is generated from these files:
	salute/salute.proto

It has these top-level messages:
	SaluteRequest
	SaluteResponse
*/
package salute

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// define enumerator ResponseType to support both html and text response types HTML and TEXT (in order)
type ResponseType int32

const (
	ResponseType_HTML ResponseType = 0
	ResponseType_TEXT ResponseType = 1
)

var ResponseType_name = map[int32]string{
	0: "HTML",
	1: "TEXT",
}
var ResponseType_value = map[string]int32{
	"HTML": 0,
	"TEXT": 1,
}

func (x ResponseType) String() string {
	return proto.EnumName(ResponseType_name, int32(x))
}
func (ResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SaluteRequest struct {
	ResponseType ResponseType               `protobuf:"varint,1,opt,name=response_type,json=responseType,enum=salute.ResponseType" json:"response_type,omitempty"`
	Saluters     []string                   `protobuf:"bytes,2,rep,name=saluters" json:"saluters,omitempty"`
	Salutee      string                     `protobuf:"bytes,3,opt,name=salutee" json:"salutee,omitempty"`
	VideoUrl     string                     `protobuf:"bytes,4,opt,name=video_url,json=videoUrl" json:"video_url,omitempty"`
	LogoUrl      string                     `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl" json:"logo_url,omitempty"`
	Description  string                     `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Url          string                     `protobuf:"bytes,7,opt,name=url" json:"url,omitempty"`
	Timestamp    *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *SaluteRequest) Reset()                    { *m = SaluteRequest{} }
func (m *SaluteRequest) String() string            { return proto.CompactTextString(m) }
func (*SaluteRequest) ProtoMessage()               {}
func (*SaluteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SaluteRequest) GetResponseType() ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return ResponseType_HTML
}

func (m *SaluteRequest) GetSaluters() []string {
	if m != nil {
		return m.Saluters
	}
	return nil
}

func (m *SaluteRequest) GetSalutee() string {
	if m != nil {
		return m.Salutee
	}
	return ""
}

func (m *SaluteRequest) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

func (m *SaluteRequest) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *SaluteRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SaluteRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SaluteRequest) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// define the SaluteResponse message to return the following fields by order:
// response_type of the enumerator type you have defined
// body (string)
type SaluteResponse struct {
	ResponseType ResponseType `protobuf:"varint,1,opt,name=response_type,json=responseType,enum=salute.ResponseType" json:"response_type,omitempty"`
	Body         string       `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *SaluteResponse) Reset()                    { *m = SaluteResponse{} }
func (m *SaluteResponse) String() string            { return proto.CompactTextString(m) }
func (*SaluteResponse) ProtoMessage()               {}
func (*SaluteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SaluteResponse) GetResponseType() ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return ResponseType_HTML
}

func (m *SaluteResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*SaluteRequest)(nil), "salute.SaluteRequest")
	proto.RegisterType((*SaluteResponse)(nil), "salute.SaluteResponse")
	proto.RegisterEnum("salute.ResponseType", ResponseType_name, ResponseType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Saluter service

type SaluterClient interface {
	Salute(ctx context.Context, in *SaluteRequest, opts ...grpc.CallOption) (*SaluteResponse, error)
}

type saluterClient struct {
	cc *grpc.ClientConn
}

func NewSaluterClient(cc *grpc.ClientConn) SaluterClient {
	return &saluterClient{cc}
}

func (c *saluterClient) Salute(ctx context.Context, in *SaluteRequest, opts ...grpc.CallOption) (*SaluteResponse, error) {
	out := new(SaluteResponse)
	err := grpc.Invoke(ctx, "/salute.Saluter/Salute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Saluter service

type SaluterServer interface {
	Salute(context.Context, *SaluteRequest) (*SaluteResponse, error)
}

func RegisterSaluterServer(s *grpc.Server, srv SaluterServer) {
	s.RegisterService(&_Saluter_serviceDesc, srv)
}

func _Saluter_Salute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaluteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaluterServer).Salute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/salute.Saluter/Salute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaluterServer).Salute(ctx, req.(*SaluteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Saluter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "salute.Saluter",
	HandlerType: (*SaluterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Salute",
			Handler:    _Saluter_Salute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "salute/salute.proto",
}

func init() { proto.RegisterFile("salute/salute.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0x4b, 0x4b, 0xc3, 0x40,
	0x10, 0x36, 0x6d, 0x4d, 0x93, 0xe9, 0x83, 0x32, 0x3e, 0x58, 0xe3, 0xc1, 0xd0, 0x53, 0xf0, 0x90,
	0x42, 0x3d, 0xa8, 0x57, 0x41, 0xf0, 0xa0, 0x97, 0x18, 0xc1, 0x5b, 0x69, 0xed, 0x58, 0x02, 0x69,
	0x37, 0xee, 0x6e, 0x84, 0xfe, 0x21, 0x7f, 0xa7, 0x64, 0xa7, 0xa9, 0xd1, 0xab, 0xa7, 0x7c, 0xaf,
	0xc9, 0xee, 0x7c, 0x0b, 0x47, 0x7a, 0x9e, 0x97, 0x86, 0x26, 0xfc, 0x89, 0x0b, 0x25, 0x8d, 0x44,
	0x97, 0x59, 0x70, 0xb1, 0x92, 0x72, 0x95, 0xd3, 0xc4, 0xaa, 0x8b, 0xf2, 0x7d, 0x62, 0xb2, 0x35,
	0x69, 0x33, 0x5f, 0x17, 0x1c, 0x1c, 0x7f, 0xb5, 0x60, 0xf0, 0x6c, 0xb3, 0x09, 0x7d, 0x94, 0xa4,
	0x0d, 0xde, 0xc2, 0x40, 0x91, 0x2e, 0xe4, 0x46, 0xd3, 0xcc, 0x6c, 0x0b, 0x12, 0x4e, 0xe8, 0x44,
	0xc3, 0xe9, 0x71, 0xbc, 0x3b, 0x20, 0xd9, 0x99, 0xe9, 0xb6, 0xa0, 0xa4, 0xaf, 0x1a, 0x0c, 0x03,
	0xf0, 0x38, 0xa4, 0xb4, 0x68, 0x85, 0xed, 0xc8, 0x4f, 0xf6, 0x1c, 0x05, 0x74, 0x19, 0x93, 0x68,
	0x87, 0x4e, 0xe4, 0x27, 0x35, 0xc5, 0x73, 0xf0, 0x3f, 0xb3, 0x25, 0xc9, 0x59, 0xa9, 0x72, 0xd1,
	0xb1, 0x9e, 0x67, 0x85, 0x17, 0x95, 0xe3, 0x19, 0x78, 0xb9, 0x5c, 0xb1, 0x77, 0xc8, 0x73, 0x15,
	0xaf, 0xac, 0x10, 0x7a, 0x4b, 0xd2, 0x6f, 0x2a, 0x2b, 0x4c, 0x26, 0x37, 0xc2, 0xb5, 0x6e, 0x53,
	0xc2, 0x11, 0xb4, 0xab, 0xb9, 0xae, 0x75, 0x2a, 0x88, 0x37, 0xe0, 0xef, 0x1b, 0x10, 0x5e, 0xe8,
	0x44, 0xbd, 0x69, 0x10, 0x73, 0x47, 0x71, 0xdd, 0x51, 0x9c, 0xd6, 0x89, 0xe4, 0x27, 0x3c, 0x9e,
	0xc1, 0xb0, 0xee, 0x89, 0x37, 0xfe, 0x4f, 0x51, 0x08, 0x9d, 0x85, 0x5c, 0x6e, 0x45, 0xcb, 0xde,
	0xcc, 0xe2, 0xcb, 0x31, 0xf4, 0x9b, 0x13, 0xe8, 0x41, 0xe7, 0x21, 0x7d, 0x7a, 0x1c, 0x1d, 0x54,
	0x28, 0xbd, 0x7f, 0x4d, 0x47, 0xce, 0xf4, 0x0e, 0xba, 0x7c, 0x09, 0x85, 0xd7, 0xe0, 0x32, 0xc4,
	0x93, 0xfa, 0xc0, 0x5f, 0xef, 0x18, 0x9c, 0xfe, 0x95, 0xf9, 0xdf, 0x0b, 0xd7, 0xee, 0x79, 0xf5,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x78, 0x47, 0x99, 0x38, 0x02, 0x00, 0x00,
}
